services:
  app:
    build:
      context: .
    ports:
      - "${PORT}:${PORT}" # Menggunakan variable dari .env
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
